dist: bionic
language: lisp

env:
  matrix:
    # - LISP=allegro
    # - LISP=ccl
    - LISP=sbcl

notifications:
  email:
    on_success: change
    on_failure: always

install:
  - curl -L https://raw.githubusercontent.com/sionescu/cl-travis/master/install.sh | sh
  # - cl -e "(cl:in-package :cl-user)
  #          (dolist (p '(:fiveam))
  #            (ql:quickload p :verbose t))"

script:
  - cl -e "(cl:in-package :cl-user)
           (prin1 (lisp-implementation-type)) (terpri) (prin1 (lisp-implementation-version)) (terpri)
           (asdf:initialize-source-registry  '(:source-registry (:directory \"./shop/shop3/\") (:tree \"./shop/jenkins/ext/\") :inherit-configuration))
           (asdf:test-system :shop3)"

sudo: required
