dist: bionic
language: lisp

env:
  matrix:
    # - LISP=allegro
    # - LISP=ccl
    - LISP=sbcl
  global:
    - PATH=${TRAVIS_BUILD_DIR}/shop-planner/shop3/jenkins/VAL/:${PATH}

notifications:
  email:
    on_success: change
    on_failure: always

install:
  - curl -L https://raw.githubusercontent.com/sionescu/cl-travis/master/install.sh | sh
  - pushd shop-planner/shop3/jenkins/VAL && make && popd 

  # - cl -e "(cl:in-package :cl-user)
  #          (dolist (p '(:fiveam))
  #            (ql:quickload p :verbose t))"

script:
  - cl -e "(cl:in-package :cl-user)
           (prin1 (lisp-implementation-type)) (terpri) (prin1 (lisp-implementation-version)) (terpri)
           (asdf:initialize-source-registry  '(:source-registry (:directory \"$TRAVIS_BUILD_DIR/shop-planner/shop3/shop3/\") (:tree \"$TRAVIS_BUILD_DIR/shop-planner/shop3/shop/jenkins/ext/\") :inherit-configuration))
           (asdf:test-system :shop3)"

sudo: required
