dist: bionic
language: lisp
services:
  - docker

env:
  matrix:
    # - LISP=allegro
    - LISP=sbcl SUITE=SHORT-PDDL-TESTS PKG=SHOP3
    - LISP=sbcl SUITE=TEST-OPENSTACKS-ADL PKG=SHOP3-OPENSTACKS
    - LISP=sbcl SUITE=TEST-OPENSTACKS-ADL-explicit-stack-search PKG=SHOP3-OPENSTACKS
    - LISP=sbcl SUITE=PLAN-OPENSTACKS PKG=SHOP3-OPENSTACKS
    - LISP=sbcl SUITE=ROVERS-TESTS PKG=SHOP3
    - LISP=sbcl SUITE=PROTECTION-TEST PKG=PROTECTION-TEST
    - LISP=sbcl PKG=ARITY-TEST SUITE=ALL-SHOP3-INTERNAL-TESTS
    - LISP=sbcl PKG=SHOP3-USER SUITE=UMT-DOMAIN-TESTS
    - LISP=sbcl PKG=SHOP3-USER SUITE=BLOCKS-TESTS
    - LISP=sbcl PKG=SHOP3-USER SUITE=LOGISTICS-TESTS
    - LISP=sbcl PKG=SHOP3-USER SUITE=SINGLETON-TESTS
    - LISP=sbcl PKG=SHOP3-USER SUITE=MISC-TESTS
    - LISP=sbcl PKG=SHOP3-USER SUITE=MINIMAL-SUBTREE-TESTS
    - LISP=sbcl PKG=SHOP3-USER SUITE=ENHANCED-PLAN-TREE
    - LISP=sbcl PKG=SHOP-THEOREM-PROVER-TESTS SUITE=THEOREM-PROVER-TESTS
    - LISP=sbcl PKG=SHOP-REPLAN-TESTS SUITE=TEST-PLAN-REPAIR

    # CCL tests must be further subdivided because its code is slower.
    - LISP=ccl SUITE=SHORT-PDDL-TESTS PKG=SHOP3
    - LISP=ccl SUITE=TEST-OPENSTACKS-ADL PKG=SHOP3-OPENSTACKS
    - LISP=ccl SUITE=TEST-OPENSTACKS-ADL-explicit-stack-search PKG=SHOP3-OPENSTACKS
    - LISP=ccl SUITE=PLAN-OPENSTACKS PKG=SHOP3-OPENSTACKS
    - LISP=ccl SUITE=ROVERS-TESTS PKG=SHOP3
    - LISP=ccl SUITE=PROTECTION-TEST PKG=PROTECTION-TEST
    - LISP=ccl PKG=ARITY-TEST SUITE=ALL-SHOP3-INTERNAL-TESTS
    - LISP=ccl PKG=SHOP3-USER SUITE=UMT-DOMAIN-TESTS
    - LISP=ccl PKG=SHOP3-USER SUITE=BLOCKS-TESTS
    - LISP=ccl PKG=SHOP3-USER SUITE=LOGISTICS-TESTS
    - LISP=ccl PKG=SHOP3-USER SUITE=SINGLETON-TESTS
    - LISP=ccl PKG=SHOP3-USER SUITE=MISC-TESTS
    - LISP=ccl PKG=SHOP3-USER SUITE=MINIMAL-SUBTREE-TESTS
    - LISP=ccl PKG=SHOP3-USER SUITE=ENHANCED-PLAN-TREE
    - LISP=ccl PKG=SHOP-THEOREM-PROVER-TESTS SUITE=THEOREM-PROVER-TESTS
    - LISP=ccl PKG=SHOP-REPLAN-TESTS SUITE=TEST-PLAN-REPAIR

notifications:
  email:
    on_success: change
    on_failure: always

install:
  - docker pull mdehavensift/shop3-test-env:latest

script:
  - docker run --rm -v $PWD:/shop3 --workdir=/shop3/jenkins -e PKG=SHOP3-USER -e SUITE=MINIMAL-SUBTREE-TESTS mdehavensift/shop3-test-env:latest ./run-tests.sh ccl run-ci-test.lisp
