dist: bionic
language: lisp

env:
  matrix:
    # - LISP=allegro
    # - LISP=ccl
    - LISP=sbcl
  suites:
    - SUITE="shop3::(pddl-tests)"
    # - SUITE="protection-test::(protection-test)"
    # - SUITE="artity-test::(arity-test io-tests method-tests)"
    # - SUITE="shop3-user::(umt-domain-tests)"
    # - SUITE="shop3-user::
    
  global:
    - PATH=${TRAVIS_BUILD_DIR}/jenkins/VAL/:${PATH}

notifications:
  email:
    on_success: change
    on_failure: always

install:
  - curl -L https://raw.githubusercontent.com/sionescu/cl-travis/master/install.sh | sh
  - ls ${TRAVIS_BUILD_DIR}/shop3/
  - pushd  ${TRAVIS_BUILD_DIR}/jenkins/VAL && make && popd 

  # - cl -e "(cl:in-package :cl-user)
  #          (dolist (p '(:fiveam))
  #            (ql:quickload p :verbose t))"

script:
  - cl -e "(cl:in-package :cl-user)
           (prin1 (lisp-implementation-type)) (terpri) (prin1 (lisp-implementation-version)) (terpri)
           (asdf:initialize-source-registry  '(:source-registry (:directory \"$TRAVIS_BUILD_DIR/shop3/\") (:tree \"$TRAVIS_BUILD_DIR/jenkins/ext/\") :inherit-configuration))
           (asdf:load-system :shop3/test)
           (defparameter *tests* (quote ${SUITE}))
           (format t \"Tests are: ~a~%\" *tests*)
           (uiop:quit (if (some (lambda (x) (typep x 'fiveam::test-failure))
                                          (loop :for x :in *tests*
                                           collecting (fiveam:run x)))
                          1 0))"

sudo: required
